language: node_js

# osx backlog is often deep, so to be polite we can just hit these highlights
matrix:
  include:
  - os: osx
    env: ESLINT_VERSION=5
    node_js: 14
  - os: osx
    env: ESLINT_VERSION=5
    node_js: 12
  - os: osx
    env: ESLINT_VERSION=5
    node_js: 10
  - os: osx
    env: ESLINT_VERSION=4
    node_js: 8
  - os: osx
    env: ESLINT_VERSION=3
    node_js: 6
  - os: osx
    env: ESLINT_VERSION=2
    node_js: 4

  fast_finish: true

before_install:
  - 'nvm install-latest-npm'
  - 'npm install'
  - 'npm run copy-metafiles'
install:
  - 'npm install'
  - 'if [ -n "${ESLINT_VERSION}" ]; then ./tests/dep-time-travel.sh; fi'

script:
  - npm run tests-only

after_success:
  - npm run coveralls
